version: "2"

checks:
  file-lines:
    config:
      threshold: 350
  method-lines:
    config:
      threshold: 30
  method-count:
    config:
      threshold: 30

engines:
  duplication:
    enabled: true
    config:
      languages:
        typescript:
          # make it higher so it does not report bullshit like similarity of abstract method and its implementation
          mass_threshold: 55
