version: "2"

checks:
  file-lines:
    config:
      threshold: 500
  method-lines:
    config:
      threshold: 50
  method-count:
    config:
      threshold: 50
  return-statements:
    config:
      threshold: 7
  method-complexity:
    config:
      threshold: 7

plugins:
  duplication:
    enabled: true
    config:
      count_threshold: 3
      languages:
        typescript:
          # make it higher so it does not report bullshit like similarity of abstract method and its implementation
          mass_threshold: 80

exclude_patterns:
  - '**/*ExceptionConverter.ts'
  - 'packages/core/src/utils/EntityComparator.ts'
  - 'docs/'
  - 'temp/'
  - '**/dist/'
  - '**/node_modules/'
  - '**/tests/'
  - '**/*.d.ts'
