name: tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2-beta
      with:
        node-version: ${{ matrix.node-version }}

    - name: EditorConfig Lint
      uses: docker://mstruebing/editorconfig-checker:2.3.3@sha256:0d95de7967db36c6add7f02495c5cdf80a9e2a791851e59fdf1699a7c7683e8d

    - name: Install libkrb5-dev (for run-rs)
      run: |
        sudo apt update
        sudo apt install libkrb5-dev

    - name: Init docker
      run: docker-compose up -d

    - name: Cache node_modules
      uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-${{ matrix.node-version }}-modules-${{ hashFiles('**/yarn.lock') }}

    - name: Install
      run: |
        yarn config set ignore-engines true
        yarn

    - name: Set CC Required env vars
      run: export GIT_BRANCH=$GITHUB_HEAD_REF && export GIT_COMMIT_SHA=$(git rev-parse origin/$GITHUB_HEAD_REF)

    - name: Lint
      run: yarn lint

    - name: Check for changes
      id: changed_packages
      run: |
        echo "::set-output name=changed_packages::$(node ./node_modules/.bin/lerna changed -p | wc -l | xargs)"

    - name: Check for changes 2
      if: steps.changed_packages.outputs.changed_packages == '0'
      run: |
        echo "no changes detected by lerna"

    - name: Build
      if: steps.changed_packages.outputs.changed_packages != '0'
      run: yarn build

    - name: Test
      if: steps.changed_packages.outputs.changed_packages != '0'
      run: |
        yarn run-rs-in-background
        yarn coverage > COVERAGE_RESULT
        echo "$(cat COVERAGE_RESULT)"
      env:
        TZ: Europe/Prague # use different timezone than UTC, because we need to validate that time zone shifting works

    - name: Release dev version for testing
      if: github.ref == 'refs/heads/master' && matrix.node-version == '15.x' && steps.changed_packages.outputs.changed_packages != '0'
      run: |
        echo "access=public" >> .npmrc
        echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc
        git fetch --depth=1 origin +refs/tags/*:refs/tags/*
        yarn publish:next --yes --no-verify-access
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Coveralls
      if: steps.changed_packages.outputs.changed_packages != '0'
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Codeclimate
      if: steps.changed_packages.outputs.changed_packages != '0'
      uses: paambaati/codeclimate-action@v2.7.5
      env:
        CC_TEST_REPORTER_ID: e2a39c5dc1a13674e97e94a467bacfaec953814982c7de89e9f0b55031e43bd8
      with:
        coverageCommand: echo "$(cat COVERAGE_RESULT)"

    - name: Teardown docker
      run: docker-compose down
